[config]
skip_core_tasks = true
default_to_workspace = false

[tasks.up-db]
command = "docker"
args = [
    "compose",
    "up",
    "-d"
]

[tasks.run-server]
command = "cargo"
args = ["run", "--package", "entrypoint"]

[tasks.up]
dependencies = ["up-db", "run-server"]

[tasks.pretty]
cwd = "server"
command = "makers"
args = ["pretty"]
