extend = "../Makefile.common.toml"

[tasks.generate-entity-for-windows]
env_files = [
    "..\\.env"
]
command = "sea-orm-cli"
args = [
    "generate",
    "entity",
    "--database-url",
    "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}",
    "-o",
    "src/entities/"
]

[tasks.generate-entity-for-others]
env_files = [
    "..//.env"
]
command = "sea-orm-cli"
args = [
    "generate",
    "entity",
    "--database-url",
    "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}",
    "-o",
    "src/entities/"
]
