//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "form_questions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub question_id: i32,
    pub form_id: i32,
    pub title: String,
    pub description: String,
    pub answer_type: String,
    pub choices: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
