[config]
skip_core_tasks = true
default_to_workspace = false

[env]
__CARGO_FIX_YOLO = 1
REPOSITORY_ROOT = { script = ["git rev-parse --show-superproject-working-tree --show-toplevel"] }

[tasks.generate-migrate-file]
command = "sea-orm-cli"
args = ["migrate", "generate", "${@}"]

[tasks.fix]
command = "cargo"
args = ["clippy", "--fix", "--allow-dirty", "--allow-staged"]

[tasks.doctest]
command = "cargo"
args = ["test", "--doc"]

[tasks.nextest]
install_crate = { crate_name = "cargo-nextst" }
command = "cargo"
args = ["nextest", "run"]

[tasks.test]
dependencies = ["nextest", "doctest"]

[tasks.lint]
command = "cargo"
args = ["clippy", "--", "-D", "warnings"]

[tasks.format]
toolchain = "nightly"
command = "cargo"
args = ["fmt", "--", "--config-path=${REPOSITORY_ROOT}/.cargo-husky/hooks/rustfmt.toml", "--emit=files"]

[tasks.pretty]
dependencies = ["fix", "test", "lint", "format"]

[tasks.udeps]
install_crate = { crate_name = "cargo-udeps" }
toolchain = "nightly"
command = "cargo"
args = ["udeps", "--all-targets", "--all-features"]

[tasks.sort]
install_crate = { crate_name = "cargo-sort" }
command = "cargo"
args = ["sort", "-wg"]
