[package]
name = "common"
version.workspace = true
edition = "2024"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = { workspace = true }
chrono = { workspace = true }
envy = { workspace = true }
proptest = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
