//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.3

pub use super::answer_types::Entity as AnswerTypes;
pub use super::form_questions::Entity as FormQuestions;
pub use super::forms::Entity as Forms;
