name: Security Audit
on:
  schedule:
    # Runs every day at 00:00 UTC
    # https://crontab.guru/#0_0_*_*_*
    - cron: "0 0 * * *"
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions-rust-lang/audit@72c09e02f132669d52284a3323acdb503cfc1a24 # v1
        with:
          workingDirectory: .
