name: Checking
on:
  push:

env:
  image_name: ghcr.io/giganticminecraft/seichi-poral-backend
  RUST_BACKTRACE: full

jobs:
  rustfmt:
    name: rustfmt check
    runs-on: ubuntu-latest
    env:
      RUST_VERSION: "$(grep -oP '(?<=channel = \").*(?=\")' rust-toolchain.toml)"
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          target: ${{ matrix.cross-target }}
          components: rustfmt
      - name: Rustfmt check
        run: cargo fmt --all -- --check
        working-directory: ./server

  lint-and-test:
    needs: [ rustfmt ]
    name: Lint and test server
    env:
      MYSQL_DATABASE: "seichi_portal"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_HOST: "localhost"
      MYSQL_PORT: "3306"
      HTTP_PORT: "9000"
      FRONTEND_URL: "http://localhost:3000"
      ENV_NAME: "local"
      REDIS_HOST: "localhost"
      REDIS_PORT: "6379"
      MEILISEARCH_HOST: "http://localhost:7700"
      RABBITMQ_USER: "user"
      RABBITMQ_PASSWORD: "password"
      RABBITMQ_HOST: "localhost"
      RABBITMQ_PORT: "5672"
      RABBITMQ_ROUTING_KEY: "seichi_portal"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "RUST_VERSION=$(sed -n 's/channel = "\(.*\)\"/\1/p' rust-toolchain.toml)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: rust-${{ env.RUST_VERSION }}-build-${{ hashFiles('**/Cargo.toml') }}
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ~/.cache/sccache/
            target/
          restore-keys: |
            rust-${{ env.RUST_VERSION }}-build-
            rust-${{ env.RUST_VERSION }}-
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy, rustfmt
      - uses: mozilla-actions/sccache-action@v0.0.9
        with:
          version: "v0.10.0"
      - run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
      - name: Configure Cache Env
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Cargo build
        run: cargo build
        working-directory: ./server

      - uses: LoliGothick/clippy-check@v0.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          deny: warnings
          working-directory: ./server

      - name: Cargo test
        run: cargo test --all-features
        working-directory: ./server

      - name: Docker compose up
        run: docker compose up -d

      - name: Wait for database to be ready
        run: |
          echo "Waiting for database to be ready..."
          timeout 60s bash -c 'until nc -z $MYSQL_HOST $MYSQL_PORT; do sleep 1; done'
          echo "Database is ready!"

      - name: Run seichi-portal-backend
        run: ./entrypoint &
        working-directory: ./server/target/debug

      # TODO: 実装している API のバージョンを取得できるようにして、自動で埋め込みたい
      - name: Save openapi schema
        run: curl https://giganticminecraft.github.io/seichi-portal-api-schema/v0.0.1/openapi.yaml -O

      - name: Run API test
        uses: schemathesis/action@v2
        with:
          schema: "./openapi.yaml"
          base-url: "http://localhost:9000"

      - name: Clean up
        if: always()
        run: docker compose down
