//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::{
    answer_types::Entity as AnswerTypes, form_choices::Entity as FormChoices,
    form_questions::Entity as FormQuestions, forms::Entity as Forms,
};
