//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

pub use super::{
    answers::Entity as Answers, form_choices::Entity as FormChoices,
    form_meta_data::Entity as FormMetaData, form_questions::Entity as FormQuestions,
    form_webhooks::Entity as FormWebhooks, real_answers::Entity as RealAnswers,
    response_period::Entity as ResponsePeriod,
};
