//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "response_period")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub form_id: i32,
    pub start_at: DateTime,
    pub end_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::form_meta_data::Entity",
        from = "Column::FormId",
        to = "super::form_meta_data::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    FormMetaData,
}

impl Related<super::form_meta_data::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FormMetaData.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
