//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "question_type")]
pub enum QuestionType {
    #[sea_orm(string_value = "text")]
    Text,
    #[sea_orm(string_value = "check_box")]
    CheckBox,
    #[sea_orm(string_value = "pull_down")]
    PullDown,
}
